version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: midnight
      POSTGRES_PASSWORD: midnight
      POSTGRES_DB: payment_app
    ports:
      - "5441:5432"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "wallet-updates:1:1,deposit-requests:1:1,transaction-status-updates:1:1"
    depends_on:
      - zookeeper

  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - kafka

  zookeeper:
    image: wurstmeister/zookeeper
